# Generated by Django 5.0.1 on 2024-08-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currently_playing_match',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wgl_api.match'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
