# Generated by Django 5.0.1 on 2025-01-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='queues_for',
            field=models.ManyToManyField(blank=True, related_name='players_in_queue', to='wgl_api.category'),
        ),
    ]
