# Generated by Django 5.0.1 on 2024-01-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='queue',
        ),
        migrations.AddField(
            model_name='player',
            name='queueing_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_queue', to='wgl_api.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('Win for Player 1', 'Player 1'), ('Win for Player 2', 'Player 2'), ('Draw', 'Draw')], max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
