# Generated by Django 5.0.1 on 2024-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='players are unique',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('player_1', models.F('player_2')), _negated=True), name='different_players'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('player_1_score', models.F('player_2_score')), _negated=True), name='different_scores'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('player_1_video_url', models.F('player_2_video_url')), _negated=True), name='different_video_urls'),
        ),
    ]
