# Generated by Django 5.0.1 on 2025-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0002_alter_player_queues_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='require_all_livestreams',
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_livestreamers',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='require_livestreams',
            field=models.BooleanField(default=False),
        ),
    ]
