# Generated by Django 5.0.1 on 2024-01-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0002_remove_game_queue_player_queueing_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elo',
            name='elo',
        ),
        migrations.AddField(
            model_name='elo',
            name='mu',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='elo',
            name='sigma',
            field=models.FloatField(default=500.0),
        ),
    ]
