# Generated by Django 5.0.1 on 2024-01-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0003_remove_elo_elo_elo_mu_elo_sigma'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='different_video_urls',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('player_1_video_url__isnull', True), ('player_2_video_url__isnull', True)), models.Q(('player_1_video_url', models.F('player_2_video_url')), _negated=True), _connector='OR'), name='different_video_urls'),
        ),
    ]
