# Generated by Django 5.0.1 on 2024-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0003_alter_match_p1_mu_after_alter_match_p2_mu_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='p1_sigma_after',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
