# Generated by Django 5.0.1 on 2024-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0004_alter_match_p1_sigma_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='p2_sigma_after',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
