# Generated by Django 5.0.1 on 2024-01-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0004_remove_match_different_video_urls_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='different_scores',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='different_video_urls',
        ),
    ]
