# Generated by Django 5.0.1 on 2024-01-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0005_remove_match_different_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_2_score',
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('1', 'Player 1 wins'), ('2', 'Player 2 wins'), ('D', 'Draw')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='yt_username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
