# Generated by Django 5.0.1 on 2024-02-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0006_alter_match_p1_score_alter_match_p2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='p1_score_formatted',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_score_formatted',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_score',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_score',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
