# Generated by Django 5.0.1 on 2024-01-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0007_alter_match_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='yt_username',
            new_name='yt_channel_id',
        ),
    ]
