# Generated by Django 5.0.1 on 2024-01-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0008_rename_yt_username_player_yt_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='yt_channel_id',
            new_name='yt_username',
        ),
    ]
