# Generated by Django 5.0.1 on 2024-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0011_game_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='shortcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
