# Generated by Django 5.0.1 on 2024-02-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0012_alter_game_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='best_of',
        ),
        migrations.RemoveField(
            model_name='game',
            name='require_livestream',
        ),
    ]
