# Generated by Django 5.0.1 on 2024-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0013_remove_game_best_of_remove_game_require_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='require_all_livestreams',
            field=models.BooleanField(default=True),
        ),
    ]
