# Generated by Django 5.0.1 on 2024-03-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0014_team_teamplayer_remove_match_different_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wgl_api.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='wgl_api.teamplayer'),
        ),
    ]
