# Generated by Django 5.0.1 on 2024-05-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0018_remove_player_youtube_player_yt_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='idd',
        ),
    ]
