# Generated by Django 5.0.1 on 2024-05-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0019_rename_game_id_game_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='idd',
            new_name='game_id',
        ),
    ]
