# Generated by Django 5.0.1 on 2024-05-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0020_rename_idd_game_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
    ]
