# Generated by Django 5.0.1 on 2024-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0022_youtube_remove_player_yt_username_player_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
