# Generated by Django 5.0.1 on 2024-05-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0023_alter_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_ids',
        ),
    ]
