# Generated by Django 5.0.1 on 2024-05-23 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0027_teamplayer_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wgl_api.match'),
        ),
    ]
