# Generated by Django 5.0.1 on 2024-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0028_alter_teamplayer_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_formatted',
            field=models.CharField(default='hi', editable=False, max_length=12),
            preserve_default=False,
        ),
    ]
