# Generated by Django 5.0.1 on 2024-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0029_alter_team_score_alter_team_score_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score_formatted',
            field=models.CharField(editable=False, max_length=12, null=True),
        ),
    ]
