# Generated by Django 5.0.1 on 2024-05-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0032_match_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='places',
        ),
        migrations.RemoveField(
            model_name='team',
            name='place',
        ),
    ]
