# Generated by Django 5.0.1 on 2024-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0037_remove_team_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.SmallIntegerField(null=True),
        ),
    ]
