# Generated by Django 5.0.1 on 2024-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0038_team_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='queueing_for',
        ),
        migrations.AddField(
            model_name='player',
            name='queues_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='players_in_queue', to='wgl_api.game'),
        ),
    ]
