# Generated by Django 5.0.1 on 2024-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0039_remove_player_queueing_for_player_queues_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
