# Generated by Django 5.0.1 on 2024-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0041_remove_teamplayer_predictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='sigma_after',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
