# Generated by Django 5.0.1 on 2024-05-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0014_game_require_all_livestreams'),
        ('wgl_api', '0043_remove_team_predictions'),
    ]

    operations = [
    ]
