# Generated by Django 5.0.1 on 2024-05-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0044_merge_20240529_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='require_all_livestreams',
        ),
    ]
