# Generated by Django 5.0.1 on 2024-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0045_remove_game_require_all_livestreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='require_all_livestreams',
            field=models.BooleanField(default=False),
        ),
    ]
