# Generated by Django 5.0.1 on 2024-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0046_game_require_all_livestreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='mu_delta',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='require_all_livestreams',
            field=models.BooleanField(default=True),
        ),
    ]
