# Generated by Django 5.0.1 on 2024-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0047_teamplayer_mu_delta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='mu_delta',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
