# Generated by Django 5.0.1 on 2024-05-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0048_alter_teamplayer_mu_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wgl_api.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='game',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wgl_api.game'),
            preserve_default=False,
        ),
    ]
