# Generated by Django 5.0.1 on 2024-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0050_alter_team_team_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elo',
            name='mu',
            field=models.SmallIntegerField(default=1500),
        ),
    ]
