# Generated by Django 5.0.1 on 2024-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0051_alter_elo_mu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='mu_after',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='mu_before',
            field=models.SmallIntegerField(default=1),
        ),
    ]
