# Generated by Django 5.0.1 on 2024-06-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgl_api', '0052_alter_teamplayer_mu_after_alter_teamplayer_mu_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currently_playing_match',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wgl_api.match'),
            preserve_default=False,
        ),
    ]
